# Generated by Django 2.2.11 on 2022-09-13 16:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('e9fdbcf2-6579-4b8e-a629-2b1cfd91a52c'), editable=False),
        ),
    ]
