# Generated by Django 4.1.1 on 2023-01-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, default='fg', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
