# Generated by Django 4.0.4 on 2022-09-12 16:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_first_name_alter_customuser_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('19d0b1c8-a6ff-462e-aae8-f2ca99b58523'), editable=False),
        ),
    ]
