# Generated by Django 2.2.11 on 2022-09-13 16:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220913_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('e7ba4662-7645-41c9-be00-5fda10681484'), editable=False),
        ),
    ]
