# Generated by Django 4.1 on 2022-08-12 10:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='id',
        ),
        migrations.AddField(
            model_name='otp',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('796cbba9-9362-4843-ad76-8e20bf8d89cf'), editable=False, primary_key=True, serialize=False),
        ),
    ]
