# Generated by Django 4.0.4 on 2022-09-12 16:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_otp_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('4bccde8b-1949-4ea3-ba7c-169f18c97fb1'), editable=False),
        ),
    ]
