# Generated by Django 4.1 on 2022-08-12 10:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_otp_id_otp_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otp',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('e2d719c7-b0c8-4d4f-8f2c-9ae2222f53ff'), editable=False),
        ),
    ]
