# Generated by Django 4.0.4 on 2022-09-12 17:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_otp_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('8f57acd9-76f8-4d67-a060-3fca2a61822c'), editable=False),
        ),
    ]
