# Generated by Django 4.1 on 2022-08-12 10:29

import accounts.utils
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_otp_id_alter_otp_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_code',
            field=models.CharField(default=accounts.utils.generate_otp, max_length=6),
        ),
        migrations.AlterField(
            model_name='otp',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('3766f1a5-f171-49ae-a548-acef2d972294'), editable=False),
        ),
    ]
