# Generated by Django 4.1 on 2022-08-12 10:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_otp_otp_code_alter_otp_request_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='otp_code',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='otp',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('f4fced4e-1a1c-4973-9f37-200d10f2b0de'), editable=False),
        ),
    ]
