# Generated by Django 4.0.4 on 2022-09-12 17:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_otp_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('5946b874-3b5d-4ba6-9bb2-84918ef60270'), editable=False),
        ),
    ]
