# Generated by Django 4.0.4 on 2022-09-12 17:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_otp_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('f6215363-e7a6-4e1e-bef7-ab86adab01b8'), editable=False),
        ),
    ]
