# Generated by Django 4.1 on 2022-08-12 11:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_otp_code_otp_code_alter_otp_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='otp',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('67f6a4e0-f3ae-4c8b-a134-60669cd04ef5'), editable=False),
        ),
    ]
