# Generated by Django 4.1 on 2022-08-14 18:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_phone_number_alter_otp_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('2f60c8d4-05a9-432c-98cf-0ddd035a3499'), editable=False),
        ),
    ]
