# Generated by Django 4.1 on 2022-08-15 14:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_otp_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('90b4e77d-42ea-4b50-8ccf-681c84d8a2a0'), editable=False),
        ),
    ]
