# Generated by Django 4.0.4 on 2022-09-12 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transition.category')),
            ],
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_milis', models.PositiveBigIntegerField()),
                ('time_local', models.CharField(max_length=100)),
                ('time_type', models.IntegerField()),
                ('description', models.TextField()),
                ('operation', models.CharField(choices=[('RE', 'وام'), ('DB', 'بدهی'), ('BY', 'خرید')], max_length=10)),
                ('bank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transition.banks')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transition.category')),
                ('sub_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transition.subcategory')),
            ],
        ),
    ]
