# Generated by Django 4.0.4 on 2022-09-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transition',
            name='operation',
            field=models.CharField(choices=[('Rent', 'وام'), ('Debt', 'بدهی'), ('Buy', 'خرید')], max_length=10),
        ),
    ]
