# Generated by Django 4.0.4 on 2022-09-12 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transition', '0002_alter_transition_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transition',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transition.banks'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transition.category'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transition.subcategory'),
        ),
    ]
