# Generated by Django 4.0.4 on 2022-09-12 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transition', '0003_alter_transition_bank_alter_transition_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transition',
            name='created',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transition',
            name='updated',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transition',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transition',
            name='time_local',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transition',
            name='time_milis',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transition',
            name='time_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
