# Generated by Django 4.0.4 on 2022-09-12 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transition', '0004_transition_created_transition_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='transition',
            name='name',
            field=models.CharField(default='خرید', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transition',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transition.bank'),
        ),
        migrations.DeleteModel(
            name='Banks',
        ),
    ]
